language: objective-c
osx_image: xcode7.2

cache:
  - /Library/Rubymotion
  - /usr/local/bin/

before_install:
  - sudo motion update --verbose
  - which motion
  - sleep 3

install: true
script: true
